---Tier 1
modimport "main/envutil"
---Tier 2
modimport "main/assets"
modimport "main/prefabfiles"
modimport "main/derives"
modimport "main/tuning"
modimport "main/language"
modimport "main/skins"
modimport "main/constants"
modimport "main/skill2cmp"
---Tier 3
modimport "main/preparedfoods"
modimport "main/recipes"
modimport "main/postinit"
modimport "main/fx"
modimport "main/actions"
modimport "main/componentactions"
modimport "main/characters"
modimport "main/networkrpc"
---Tier 4
modimport "main/debugcommands"
modimport "main/scrapbook_kmds"